//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelExperts_WebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CreditCard
    {
        public int CreditCardId { get; set; }
        [Required(ErrorMessage = "Please enter the card type (AMEX/Visa/Diners/MC).")]
        public string CCName { get; set; }
        [Required(ErrorMessage = "Please enter the card number.")]
        public string CCNumber { get; set; }
        [Required(ErrorMessage = "Please enter the card expiry date.")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:MM-yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime CCExpiry { get; set; }
        public int CustomerId { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
