//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelExperts_WebApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.Bookings = new HashSet<Booking>();
            this.CreditCards = new HashSet<CreditCard>();
            this.Customers_Rewards = new HashSet<Customers_Rewards>();
        }
        [Key]
        public int CustomerId { get; set; }
        [Required(ErrorMessage ="Please enter your first name.")]
        public string CustFirstName { get; set; }
        [Required(ErrorMessage = "Please enter your last name.")]
        public string CustLastName { get; set; }
        [Required(ErrorMessage = "Please enter your address.")]
        public string CustAddress { get; set; }
        [Required(ErrorMessage = "Please enter the city in which you reside.")]
        public string CustCity { get; set; }
        [Required(ErrorMessage = "Please enter the province in which you reside.")]
        public string CustProv { get; set; }
        [Required(ErrorMessage = "Please enter your postal code.")]
        [DataType(DataType.PostalCode)]
        [RegularExpression(@"^[ABCEGHJ-NPRSTVXY]{1}[0-9]{1}[ABCEGHJ-NPRSTV-Z]{1}[ ]?[0-9]{1}[ABCEGHJ-NPRSTV-Z]{1}[0-9]{1}$", 
            ErrorMessage = "Invalid postal code.")]
        public string CustPostal { get; set; }
        [Required(ErrorMessage = "Please enter the country in which you reside.")]
        public string CustCountry { get; set; }
        [Required(ErrorMessage = "Please enter your home phone number.")]
        public string CustHomePhone { get; set; }
        [Required(ErrorMessage = "Please enter your business phone number.")]
        public string CustBusPhone { get; set; }
        [Required(ErrorMessage = "Please enter E-mail address.")]
        [DataType(DataType.EmailAddress)]
        [EmailAddress]
        public string CustEmail { get; set; }
        public Nullable<int> AgentId { get; set; }
        //[Required(ErrorMessage = "Please enter a password.")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Booking> Bookings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CreditCard> CreditCards { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers_Rewards> Customers_Rewards { get; set; }
    }
}
